import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{ArrowRight,CalendarDays,CheckCircle2,Clock3,HeartHandshake,LogIn,MapPin,Menu,Search,ShieldCheck,Sparkles,UserRound,Users,X}from"lucide-react";
import{supabase,supabaseConfigured}from"./supabase";
import"./styles.css";

const fallback=[["Errands & Shopping","Grocery shopping and everyday errands"],["Home Help","Practical household assistance"],["Senior Support","Non-medical senior assistance and companionship"],["Local Travel Assistance","Accompaniment for local travel and appointments"],["Pickup & Delivery","Local pickup and delivery assistance"],["Companionship","Friendly social companionship"],["Digital Help","Basic phone, app and online assistance"],["Other Everyday Help","Other permitted everyday assistance"]];

function App(){
 const[page,setPage]=useState("home"),[menu,setMenu]=useState(false),[services,setServices]=useState([]),[session,setSession]=useState(null),[profile,setProfile]=useState(null),[notice,setNotice]=useState("");
 const go=p=>{setPage(p);setMenu(false);window.scrollTo(0,0)};
 useEffect(()=>{if(!supabase){setServices(fallback.map((x,i)=>({id:i+1,name:x[0],description:x[1],active:true})));return}
  supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)loadProfile(data.session.user.id)});
  const l=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)loadProfile(s.user.id);else setProfile(null)});
  loadServices();return()=>l.data.subscription.unsubscribe()
 },[]);
 async function loadServices(){const{data,error}=await supabase.from("services").select("*").eq("active",true).order("id");if(error)setServices(fallback.map((x,i)=>({id:i+1,name:x[0],description:x[1],active:true})));else setServices(data||[])}
 async function loadProfile(id){const{data}=await supabase.from("profiles").select("*").eq("id",id).maybeSingle();setProfile(data||null)}
 async function logout(){if(supabase)await supabase.auth.signOut();go("home")}
 return <div className="app"><header className="nav"><button className="brand" onClick={()=>go("home")}><span className="brandMark">AI</span><span><b>APNA INSAAN</b><small>A person you can count on.</small></span></button><nav className={menu?"navLinks open":"navLinks"}><button onClick={()=>go("home")}>Home</button><button onClick={()=>go("find")}>Find a Person</button><button onClick={()=>go("assistant")}>Become an Apna Insaan</button><button onClick={()=>go("safety")}>Safety</button>{session?<button className="loginBtn" onClick={()=>go("account")}><UserRound size={17}/> My Account</button>:<button className="loginBtn" onClick={()=>go("login")}><LogIn size={17}/> Login</button>}</nav><button className="menuBtn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 {notice&&<div className="notice">{notice}<button onClick={()=>setNotice("")}><X size={15}/></button></div>}
 <main>{page==="home"&&<Home go={go} services={services}/>}
 {page==="find"&&<Find go={go} services={services}/>}
 {page==="login"&&<Login go={go} setNotice={setNotice} loadProfile={loadProfile}/>}
 {page==="customer"&&<Customer go={go} setNotice={setNotice}/>}
 {page==="assistant"&&<Assistant go={go} services={services} setNotice={setNotice}/>}
 {page==="account"&&<Account profile={profile} session={session} go={go} logout={logout}/>}
 {page==="safety"&&<Safety/>}</main>
 <footer><div><b>APNA INSAAN</b><p>Everyday help, booked with confidence.</p></div><div><button onClick={()=>go("safety")}>Safety</button><button onClick={()=>go("assistant")}>Join as an assistant</button></div><small>© 2026 Apna Insaan · V2</small></footer></div>
}

function Home({go,services}){return <section><div className="hero"><div><span className="eyebrow"><Sparkles size={15}/> TRUSTED PEOPLE FOR EVERYDAY HELP</span><h1>When you need someone,<br/><em>find your Apna Insaan.</em></h1><p>Book a real person for errands, companionship, local assistance and everyday tasks — with clear profiles and a safety-first approach.</p><div className="heroBtns"><button className="primary" onClick={()=>go("find")}>Find a Person <ArrowRight/></button><button className="secondary" onClick={()=>go("assistant")}>Become an Apna Insaan</button></div><div className="trust"><span><ShieldCheck/> Verification workflow</span><span><HeartHandshake/> Human connection</span><span><MapPin/> Local service</span></div></div><div className="heroCard"><div className="avatarBig">AI</div><span className="online"><i/> Available</span><h3>Your help, your choice.</h3><p>Choose the service, area and person that fits your need.</p><div className="miniStats"><b>8+<small>Services</small></b><b>24/7<small>Requests</small></b><b>1:1<small>Human support</small></b></div></div></div><div className="sectionHead"><span>WHAT CAN WE HELP WITH?</span><h2>Everyday help, made simple.</h2></div><div className="serviceGrid">{services.map(s=><button className="serviceCard" key={s.id} onClick={()=>go("find")}><span className="serviceIcon"><HeartHandshake/></span><b>{s.name}</b><p>{s.description}</p><ArrowRight/></button>)}</div><div className="how"><div><span className="eyebrow">HOW IT WORKS</span><h2>Three simple steps.</h2></div><div className="steps"><Step n="01" title="Tell us what you need" text="Choose a service and your area."/><Step n="02" title="Choose your person" text="Review profiles and availability."/><Step n="03" title="Book with confidence" text="Confirm the request and keep track."/></div></div></section>}
function Step({n,title,text}){return <div className="step"><strong>{n}</strong><div><h3>{title}</h3><p>{text}</p></div></div>}

function Find({go,services}){const[q,setQ]=useState(""),[service,setService]=useState("");const m=services.filter(s=>(!service||s.name===service)&&s.name.toLowerCase().includes(q.toLowerCase()));return <section className="page"><div className="pageIntro"><span className="eyebrow">FIND A PERSON</span><h1>Who do you need today?</h1><p>The directory is ready for assistant registrations. Verified profiles will appear here.</p></div><div className="searchBox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search services..."/><select value={service} onChange={e=>setService(e.target.value)}><option value="">All services</option>{services.map(s=><option key={s.id}>{s.name}</option>)}</select></div><div className="emptyState"><Users size={44}/><h2>Assistant directory is ready</h2><p>Once verified assistants join, customers can compare profiles, rates, availability and reviews here.</p><button className="primary" onClick={()=>go("assistant")}>Register as an Assistant <ArrowRight/></button></div><div className="serviceGrid compact">{m.map(s=><div className="serviceCard" key={s.id}><span className="serviceIcon"><HeartHandshake/></span><b>{s.name}</b><p>{s.description}</p></div>)}</div></section>}

function Login({go,setNotice,loadProfile}){const[phone,setPhone]=useState(""),[otp,setOtp]=useState(""),[sent,setSent]=useState(false),[busy,setBusy]=useState(false);
 async function send(e){e.preventDefault();if(!supabaseConfigured){setNotice("Supabase is not connected to this deployment.");return}setBusy(true);const{error}=await supabase.auth.signInWithOtp({phone});setBusy(false);if(error)setNotice(error.message);else{setSent(true);setNotice("OTP sent. Check your phone.")}}
 async function verify(e){e.preventDefault();setBusy(true);const{data,error}=await supabase.auth.verifyOtp({phone,token:otp,type:"sms"});setBusy(false);if(error)setNotice(error.message);else{await loadProfile(data.user.id);go("account")}}
 return <section className="page narrow"><div className="formCard"><span className="eyebrow">LOGIN / REGISTER</span><h1>Your Apna Insaan account</h1><p>Use your mobile number and a one-time password.</p><form onSubmit={sent?verify:send}><Field label="Mobile number" value={phone} onChange={setPhone} placeholder="+91 98765 43210" required/>{sent&&<Field label="OTP" value={otp} onChange={setOtp} placeholder="6-digit OTP" required/>}<button className="primary full" disabled={busy}>{busy?"Please wait…":sent?"Verify OTP":"Send OTP"}</button></form><div className="choice"><button onClick={()=>go("customer")}>Create Customer Profile</button><button onClick={()=>go("assistant")}>Register as Assistant</button></div>{!supabaseConfigured&&<div className="warning">Supabase environment variables are missing from this deployment.</div>}</div></section>}

function Customer({go,setNotice}){const[f,setF]=useState({full_name:"",phone:"",city:"",area:""}),[busy,setBusy]=useState(false);async function save(e){e.preventDefault();if(!supabase){setNotice("Please log in with OTP first.");go("login");return}const{data:{user}}=await supabase.auth.getUser();if(!user){setNotice("Please log in with OTP first.");go("login");return}setBusy(true);const{error}=await supabase.from("profiles").upsert({id:user.id,role:"customer",...f});setBusy(false);if(error)setNotice(error.message);else{setNotice("Customer profile saved.");go("account")}}return <section className="page narrow"><form className="formCard" onSubmit={save}><span className="eyebrow">CUSTOMER REGISTRATION</span><h1>Create your profile</h1><p>Tell us where you are so bookings can be personalised.</p><Field label="Full name" value={f.full_name} onChange={v=>setF({...f,full_name:v})} required/><Field label="Mobile" value={f.phone} onChange={v=>setF({...f,phone:v})}/><div className="two"><Field label="City" value={f.city} onChange={v=>setF({...f,city:v})} required/><Field label="Area" value={f.area} onChange={v=>setF({...f,area:v})}/></div><button className="primary full" disabled={busy}>{busy?"Saving…":"Save Customer Profile"}</button></form></section>}

function Assistant({services,go,setNotice}){const[p,setP]=useState({full_name:"",phone:"",city:"",area:""}),[x,setX]=useState({gender:"",age:"",experience_years:"",languages:"",bio:"",hourly_rate:"",availability:""}),[sel,setSel]=useState([]),[busy,setBusy]=useState(false);
 const tog=id=>setSel(a=>a.includes(id)?a.filter(v=>v!==id):[...a,id]);
 async function save(e){e.preventDefault();if(!supabase){setNotice("Please log in with OTP first.");go("login");return}const{data:{user}}=await supabase.auth.getUser();if(!user){setNotice("Please log in with OTP first.");go("login");return}if(!sel.length){setNotice("Select at least one service.");return}setBusy(true);let{error}=await supabase.from("profiles").upsert({id:user.id,role:"assistant",...p});if(!error)({error}=await supabase.from("assistants").upsert({id:user.id,...x,age:x.age?Number(x.age):null,experience_years:x.experience_years?Number(x.experience_years):null,hourly_rate:x.hourly_rate?Number(x.hourly_rate):null,verification_status:"pending"}));if(!error){await supabase.from("assistant_services").delete().eq("assistant_id",user.id);const r=await supabase.from("assistant_services").insert(sel.map(service_id=>({assistant_id:user.id,service_id})));error=r.error}setBusy(false);if(error)setNotice(error.message);else{setNotice("Assistant registration submitted for verification.");go("account")}}
 return <section className="page"><div className="pageIntro"><span className="eyebrow">ASSISTANT REGISTRATION</span><h1>Become an Apna Insaan.</h1><p>Build your profile, choose your services and submit for verification.</p></div><form className="formCard wide" onSubmit={save}><h2>Basic details</h2><div className="two"><Field label="Full name" value={p.full_name} onChange={v=>setP({...p,full_name:v})} required/><Field label="Mobile" value={p.phone} onChange={v=>setP({...p,phone:v})}/></div><div className="two"><Field label="City" value={p.city} onChange={v=>setP({...p,city:v})} required/><Field label="Area" value={p.area} onChange={v=>setP({...p,area:v})}/></div><h2>Your details</h2><div className="three"><Field label="Gender" value={x.gender} onChange={v=>setX({...x,gender:v})}/><Field label="Age" type="number" value={x.age} onChange={v=>setX({...x,age:v})}/><Field label="Experience (years)" type="number" value={x.experience_years} onChange={v=>setX({...x,experience_years:v})}/></div><div className="two"><Field label="Languages" value={x.languages} onChange={v=>setX({...x,languages:v})} placeholder="Hindi, Marathi, English"/><Field label="Hourly rate (₹)" type="number" value={x.hourly_rate} onChange={v=>setX({...x,hourly_rate:v})}/></div><Field label="Availability" value={x.availability} onChange={v=>setX({...x,availability:v})} placeholder="9 AM – 6 PM, Mon–Sat"/><label>About you<textarea value={x.bio} onChange={e=>setX({...x,bio:e.target.value})}/></label><h2>Services you offer</h2><div className="checkGrid">{services.map(s=><button type="button" className={sel.includes(s.id)?"check selected":"check"} key={s.id} onClick={()=>tog(s.id)}><span>{sel.includes(s.id)&&<CheckCircle2 size={16}/>}</span><b>{s.name}</b></button>)}</div><div className="verification"><ShieldCheck/><div><b>Verification</b><p>Your profile starts as <strong>Pending</strong> and can be approved by an admin before bookings.</p></div></div><button className="primary full" disabled={busy}>{busy?"Submitting…":"Submit Assistant Registration"}</button></form></section>}

function Field({label,value,onChange,type="text",placeholder="",required=false}){return <label>{label}<input type={type} value={value} placeholder={placeholder} required={required} onChange={e=>onChange(e.target.value)}/></label>}

function Account({profile,session,go,logout}){if(!session)return <section className="page narrow"><div className="emptyState"><UserRound/><h2>Please log in</h2><button className="primary" onClick={()=>go("login")}>Login / Register</button></div></section>;return <section className="page"><div className="accountHero"><div className="avatarBig">{(profile?.full_name||"AI").slice(0,2).toUpperCase()}</div><div><span className="eyebrow">MY ACCOUNT</span><h1>{profile?.full_name||"Welcome"}</h1><p>{profile?.role==="assistant"?"Assistant profile":"Customer profile"} · {profile?.city||"Location not added"}</p></div><button className="secondary" onClick={logout}>Sign out</button></div><div className="accountGrid"><Card icon={<CheckCircle2/>} title="Profile status" text={profile?.role==="assistant"?"Pending verification":"Customer profile active"}/><Card icon={<CalendarDays/>} title="Bookings" text="Your booking history will appear here."/><Card icon={<ShieldCheck/>} title="Safety" text="Use verified profiles and report concerns promptly."/></div></section>}
function Card({icon,title,text}){return <div className="accountCard">{icon}<h3>{title}</h3><p>{text}</p></div>}
function Safety(){return <section className="page"><div className="pageIntro"><span className="eyebrow">SAFETY FIRST</span><h1>People, not just profiles.</h1><p>Apna Insaan is designed around trust, verification and clear communication.</p></div><div className="safetyGrid"><Card icon={<ShieldCheck/>} title="Verification" text="Assistants can be reviewed and approved before receiving bookings."/><Card icon={<HeartHandshake/>} title="Clear service" text="Customers see the service, location and agreed price."/><Card icon={<Clock3/>} title="Booking record" text="Requests and statuses can be tracked."/><Card icon={<Users/>} title="Respect" text="No harassment, illegal activity or unsafe requests."/></div></section>}

createRoot(document.getElementById("root")).render(<App/>);
